const config = require('../config/config');

module.exports = {
    catBreed: [
        {
            name: "British Shorthair", species: config.species.Cat, picUrl: './images/species/cat/cat.png',
            realPicUrl: './images/breed/cat/british-shorthair.jpg', backPicUrl: './images/breed/cat/british-shorthair-back.jpg',
            information: { temperament:'Calm, easy going', lifeSpan: '8-10', price: '$1500 - $2000', avgSize:'Large', origin: 'Largest',
                color: 'Blue, Brown, Red, Silver', weight: ''},
            characteristics: { affection: 4, inquisitive: 3, bark: 2, odour: 0.5, sheddingAmount: 1},
            temperament: 'These smiling cats enjoy attention, are normally quiet, but occasionally have bursts of crazed activity before changing back into your affectionate, dignified friend. They get along with children and cat-friendly dogs.\n' +
            'British Shorthairs are calm and undemanding. Males are big, easy lugs with a happy-go-lucky nature but a natural air of command. Females are more serious. Both want only to be with their people, not necessarily in a lap or being carried around, but next to them or in the same room with them. When you’re not home, they are satisfied to entertain themselves until you return.\n' +
            'This is not a very active cat. You won’t find him on top of the refrigerator but instead solidly on the floor. He is smart and will enjoy having toys to play with, especially if they are interactive.\n' +
            'He might be laidback, but the British Shorthair is smart. Challenge his brain and keep him interested in life by teaching him tricks and providing him with puzzle toys that will reward him with kibble or treats when he learns how to manipulate them.\n' +
            'Always choose a kitten from a breeder who raises litters in the home and handles them from an early age. Meet at least one and ideally both of the parents to ensure that they have nice temperaments.',
            diet: 'British Shorthair cats are pretty much into food in general and love trying out different flavors.\n' +
            'Since the British Shorthair are muscular, their food must be high in protein and very moderate when it comes to fat. Therefore, they should eat meat – either cooked or raw, in order to grow strong and healthy. Moreover, their food should be low in carbohydrates so it is recommended to avoid potato-based meals. This is also why There are many British Shorthair breeders who prefer home-made and raw food.\n' +
            'It is also important to know that a raw diet makes this breed’s fur silkier and smoother and is therefore strongly recommended by specialists.\n' +
            'British Shorthair cat home food should be based on meat – either beef, chicken, turkey or rabbit. Home-made cat food recipes should be based on boiling the meat or vegetables in water.\n' +
            'It is important to know that fish and shrimps should not be given to your cat more than two times a week. Dairy products are welcome, as long as they are not too rich in fat.',
            housing: 'The British Shorthair is well suited to any home with people who will love him. Keep him indoors to protect him from cars, diseases spread by other cats and attacks from other animals.t',
            toys: 'N/A' ,
            clean: 'The coat of the British Shorthair can be compared to a carpet with a deep pile. They have more hairs per square inch in their coats than any other breed. Surprisingly, this luxurious coat requires very little care beyond brushing or combing with a wire toothed comb to remove dead and loose hairs. This should be done on a weekly basis to minimize shedding.',
            training: 'N/A',
            health: 'The British Shorthair is generally healthy, but he’s prone to hypertophic cardiomyopathy (HCM) and hemophilia B, a hereditary bleeding disorder. A DNA test has been developed that allows breeders to identify hemophilia B carriers or affected cats.\n' +
            'Hypertrophic cardiomyopathy (HCM) is the most common form of heart disease in cats. It causes thickening (hypertrophy) of the heart muscle. An echocardiogram can confirm whether a cat has HCM. Avoid breeders who claim to have HCM-free lines. No one can guarantee that their cats will never develop HCM. British Shorthairs that will be bred should be screened for HCM, and cats identified with HCM should be removed from breeding programs. Do not buy a kitten whose parents have not been tested for this disease.\n' +
            'Do not buy from a breeder who does not provide a written health guarantee. Remember that after you’ve taken a new kitten into your home, you have the power to protect him from one of the most common health problems: obesity.\n' +
            'Keeping a British Shorthair at an appropriate weight is one of the easiest ways to protect his overall health. Make the most of your preventive abilities to help ensure a healthier cat for life.'
        },
        {
            name: "Exotic Shorthair", species: config.species.Cat, picUrl: './images/species/cat/cat.png',
            realPicUrl: './images/breed/cat/exotic-shorthair.jpg', backPicUrl: './images/breed/cat/exotic-shorthair-back.jpg',
            information: { temperament:'Affectionate, intelligent', lifeSpan: '12-14', price: '$1500 - $2000', avgSize:'Medium', origin: 'United States',
                color: 'Black, Blue, Chinchilla, Chocolate, Cream', weight: '10-12 lb'},
            characteristics: { affection: 3.5, inquisitive: 3, bark: 2, odour: 0.5, sheddingAmount: 2},
            temperament: 'The quiet and docile Exotic Shorthair adapts easily to any environment, getting along well with dogs and children. They are much like their Persian forefathers, but are more inquisitive and outgoing, which makes for a gentle and loving playmate that is fun and active without being destructive. Even Exotic kittens are good not to tear things up, and regardless of age, Exotics rarely use their claws. They train easily, and unlike many cats, actually understand the concept of “no.” Tell an Exotic to get off the counter or table, and he will actually remember and obey. They like to be close to their humans, but Exotics are not demanding companions. They will accept an invitation, and will likely extend one, but they rarely insist. Instead, the Exotic is content to spend hours sitting looking out the window, or dozing in some favorite spot around the house. They sleep most of the day, and are most active in the evening and early morning. An Exotic can entertain himself for hours, and thus can be left alone without experiencing loneliness or separation anxiety.\n',
            diet: 'There should be a relatively stable time each day to feed the kittens. The kittens are fed 4 times a day and the cats are each one sooner or later.\n' +
            'The weight control is very simple. Before the cats eat 2 to 3 hours before each meal, pay attention to see if their rice bowls are empty. If they were empty at an earlier time, then explain the cat you gave. The food is not enough; but if you find that there are surplus cat foods in their rice bowl before the meal, it means that you have given more food, and you should reduce it appropriately.',
            housing: 'N/A',
            toys: 'N/A' ,
            clean: 'Unlike all other short-haired cats, the Exotic Shorthair’s coat is even all over, with no ruff or feathering at the tail. The dense fur has a medium soft texture. Grooming can be easily accomplished with a steel comb to prevent matting and tangling. No more than one or two sessions a week is necessary. Exotics do need the occasional bath, especially when they are shedding their winter coat. Fortunately, these cats take well to bathing and are easily handled. Care should be taken to keep the eyes clean to avoid staining in the corners.',
            training: 'N/A',
            health: 'Exotics have hereditary health issues that can be a concern, especially if you aren’t cautious about who you buy from. They include polycystic kidney disease (PKD) and a tendency to develop calcium oxylate stones in the urinary tract. Responsible breeders take steps to avoid these problems. Exotics should be healthy and vigorous, able to breathe normally and produce only normal amounts of tears.\n' +
            'Polycystic kidney disease is a hereditary condition causing enlarged kidneys and kidney dysfunction. Cysts can often be found via ultrasound by 12 months of age, although kidney failure may not occur until later. Reputable breeders are working to establish PKD-free breeding programs. Fortunately, DNA testing is available, so it is easy to identify and eliminate. Ask the breeder for proof that both of a kitten’s parents are free of kidney cysts, which can be detected on ultrasound or with a DNA test. If one of the parents is PKD positive, which may be the case if the cat’s bloodlines are otherwise valuable, confirm that the kitten you are purchasing has tested PKD negative.\n' +
            'Exotics may have breathing problems, due to their flat faces, and are sensitive to heat. They need to live in air-conditioned comfort, protected from hot weather. Keep in mind that many airlines will not transport them in the cargo bay (which isn’t recommended for other reasons, as well) because of their potential for respiratory distress or even death in stressful conditions.'
        },
        {
            name: "Siamese", species: config.species.Cat, picUrl: './images/species/cat/cat.png',
            realPicUrl: './images/breed/cat/siamese.jpg', backPicUrl: './images/breed/cat/siamese-back.jpg',
            information: { temperament:'Intelligent, Playful, Extroverts', lifeSpan: '12-15', price: '$400 - $600', avgSize:'Medium', origin: 'Thailand', color: 'Fawn, Chocolate', weight: '8-10 lb'},
            characteristics: { affection: 5, inquisitive: 5, bark: 2, odour: 0.5, sheddingAmount: 2},
            temperament: 'Siamese cats are known to be affectionate, friendly, loyal and bold. The Blue Point Siamese is said by some to be the gentlest and most affectionate of all the Colorpoint Shorthair varieties, although certainly many fanciers of the other Siamese color varieties might dispute that characterization. Siamese have been described as precocious, gregarious, intelligent and outgoing. They are extremely friendly with people and other pets that they know and like, and they thrive on companionship and affection. They form extremely close bonds with their primary caretaker and do not like to be left alone for long periods of time. They often do better kept in household pairs or small groups, so that they can entertain each other while their owners are away. Some Siamese can have a nervous personality and most do not like sudden changes in their living environment. Siamese can be aloof toward strangers and are often skittish around newcomers to the home.',
            diet: 'Siamese kittens are in the growth period of 2 to 5 months, and more calories are necessary. Cats weighing three to four months after birth need one calorie per day for 130 to 250 calories, 100 calories after six months, and 80 calories for adult cats. In terms of nutrients, basically cats are carnivores, so they need more animal protein. In addition, if calcium intake is insufficient, bones, teeth, and paws may be incompletely grown. When taurine is insufficient, blindness or rosacea may be caused. Insufficient vitamin A may also cause visual impairment or deterioration of skin condition. These nutrients may be considered. Give more. Cats need 40% more calcium in their developmental stages than in cats.',
            housing: 'N/A',
            toys: 'Scratching post, climbing furniture' ,
            clean: 'The tight, glossy coat is short and fine, adhering close to the body and requiring little in the way of special care. Many owners find that nothing more is required than a good rub down with a chamois cloth to remove loose hairs from the coat, a process the convivial Siamese enjoys enormously.',
            training: 'N/A',
            health: 'The modern Siamese cat with his wedge-shaped head may be more prone to respiratory and dental problems than cats with a less extreme head type, and some Siamese occasionally have problems with crossed eyes or a kinked tail. Other problems reported in the breed include bladder stones; eye problems like glaucoma and progressive retinal atrophy; heart problems; and certain types of cancer.\n' +
            'Remember that after you’ve taken a new kitten into your home, you have the power to protect him from one of the most common health problems: obesity. Keeping a Siamese at an appropriate weight is one of the easiest ways to protect his overall health. Make the most of your preventive abilities to help ensure a healthier cat for life.'
        }
        /*{
            name: 'Abyssinian', species: config.species.Cat, picUrl: 'http://www.petguide.com/wp-content/uploads/2013/07/abyssinian.jpg',
            information: { lifeSpan: '10-15', price: '$900 - $1200', avgSize: 'Medium', origin: 'Ethiopia' },
            characteristics: {affection: 3, inquisitive: 1, bark: 2, odour: 0.5, sheddingAmount: 1},
            temperament: 'Active, Energetic, Independent, Intelligent\n' +
                'GentleAbys are known for being exceptionally intelligent. They are also more outgoing than many breeds of cat. They are playful and have strong personalities. They are not usually lap cats but they enjoy attention from their owners. They are not as aloof or independent as some cats. They enjoy being around lots of activity and can become depressed if things are too quiet. They like to play with toys and other games with their owners.\n' +
                'Unlike some Oriental shorthair breeds such as the Siamese, Abyssinians tend to be quiet cats. They have a soft voice and do not yowl. They tend to be suspicious of strangers so if you have visitors to your home, your Abyssininian may make himself scarce. Some Abyssinians can be very timid and shy around people they don’t know. Otherwise, this is a breed that enjoys clowning around at home.',
            diet: 'Cat experts and Abyssinian breeders generally recommend food with fresh meat or canned food without grains for these cats. You should obviously make sure the food has suitable Vitamin A and taurine, but this is true for all cats. All cats need plenty of meat protein in their food and we agree with these experts that a minimum of 40 percent protein (DMB) is suitable.\n' +
                'Be sure to encourage your Aby to drink plenty of water, especially if you are putting down dry food.',
            housing: '1. Before raising Abyssinia cats must first plan their activity space, unlike other meows, Abyssinia cats like spacious rooms, if you put them in a narrow space, they will be very angry.\n' +
                '2. Prepare a cat rack for them, because Abyssinia cats like to climb trees, some people call them rock climbers, an interesting cat rack can definitely let them enjoy life. Because of this dynamic character, owners should pay attention to the maintenance of cats in the process of home fragile items away.',
            toys: 'Ping-Pong balls, bottle caps, wadded-up pieces of paper, puzzle toys and teasers',
            clean: 'Abyssinian cats are short-haired cats, so owners do not have to bathe them regularly. Under normal circumstances, they can take a bath once a month. However, to bathe them should pay particular attention to the following matters: \n' +
                'A. The water temperature can not be too low or too high, not to be hot (40 ~ 50 °C) is appropriate; indoor keep warm, prevent the cat from catching cold and cause colds. \n' +
                'B. The detergent used can not be too irritating to avoid irritating the skin. To prevent bath water from entering the eyes, the cat\'s eyes should be oiled with eye drops before the bath to protect the eyes. \n' +
                'C. Cats should not take a bath when they are in poor health. Kittens within 6 months of age are prone to getting sick and generally do not take a shower.'
        }*/
        ]
};

