const config = require('../config/config');

module.exports = {
    rabbitBreed: [
        {
            name: "American Rabbit", species: config.species.Rabbit, picUrl: './images/species/rabbit/rabbit.png',
            realPicUrl: 'http://www.petguide.com/wp-content/uploads/2016/05/american-rabbit.jpg', backPicUrl: 'http://www.petguide.com/wp-content/uploads/2016/05/american-rabbit-2.jpg',
            information: { temperament:'Docile, quiet, calm, laid-back', lifeSpan: '8-12', price: '', avgSize:'Medium', origin: 'American',
            color:'white, grey', weight:'9-11 lb'},
            characteristics: { affection: -1, inquisitive: -1, bark: -1, odour: -1, sheddingAmount: -1},
            temperament: 'Docile, quiet, calm, laid-back\n' +
            'This breed was mostly used for commercial meat and fur purposes back in the 1900s and less of a pet. This means you can expect it to be calm, docile, and have an easy-going attitude even around humans.\n' +
            'Depending on whether or not they were raised in close proximity to humans or always near their litter mates, they may be a little skittish around people, especially those with smaller hands and aren’t really sure of how to approach them. It is for that reason that this rabbit is not completely recommended for families with younger children, as the rabbit can suddenly become scared and defend itself by nipping at the person’s hand. While an adult will understand it was simply instinct, a child won’t be so quick to forgive. It’s all in the way and the environment in which they were raised.\n' +
            'Some bunnies are full of energy and love to hop about for hours on end in a backyard. Most American rabbits are rather docile with some just barely sipping into the “lazy” side of the scale. If you’re looking for a companion bunny who loves to hang out, this guy is definitely for you.',
            diet: 'In terms of food, rabbits will enjoy a diet comprised mostly of pellets and hay (about 70 percent). Adult rabbits will eat about 1/4 cup of high-fiber pellets every day for every 5 pounds they weigh. They also enjoy fresh fruits and vegetables including carrots, watercress, red or green lettuce, celery, mango, pear, peach, and much more.',
            housing: 'When it comes to buying an enclosure for your rabbit, you have quite a few options. You can opt to have an indoor rabbit cage or purchase a dog crate and add some nifty bunny-friendly modifications, which is great for apartment dwellers. If you have a little bit more room outdoors or even have your own fenced backyard, you can purchase or build your own rabbit hutch or even a rabbit shed! But whenever you have an outdoor enclosure for your rabbit, always be aware of outdoor temperatures, how much sun your rabbit is exposed to and if there are any local predators you should be wary of (racoons, birds, coyotes, etc).',
            toys: '' ,
            clean: 'Most rabbits are immaculately clean, and since washing them is an absolute no-no, groom your bunny with a brush a few times a month to keep their fur in tip-top shape.',
            training: '',
            health: 'If you wish to have your doe spayed, you can do so as soon as they are four months of age. Most veterinarians prefer to wait until they are 6 months old as the older they are, the less risk there is on the operating table. Bucks can be neutered as young as 3 1/2 months of age.\n' +
            'The breed is not at-risk for any particular health problems, but bunnies (both domestic and commercial) are always susceptible to a number of health issues. This includes snuffles, hairballs, uterine tumors, calicivirus, myxomatosis, and overgrown teeth. The latter is completely preventable. Usually, rabbits who have a high-fiber diet of hay won’t have this issue, as their teeth wear down from chewing on this harsh food. If you find your rabbit’s teeth seem to be growing a little faster than they are wearing down, providing straw or wicker mats, rabbit-safe blocks of wood, or straw baskets are a great way for them to have fun and wear their teeth down.'
        },
        {
            name: "American Fuzzy Lop", species: config.species.Rabbit,  picUrl: './images/species/rabbit/rabbit.png',
            realPicUrl: 'http://www.petguide.com/wp-content/uploads/2016/05/american-fuzzy-lop.jpg', backPicUrl: 'http://www.petguide.com/wp-content/uploads/2016/05/american-fuzzy-lop-1.jpg',
            information: { temperament:'Playful, active, curious, affectionate', lifeSpan: '5-8', price: '', avgSize:'Small', origin: 'American',
            color:'Chestnut, Chinchilla, Lynx, Opal and Squirrel', weight:'3.5- 4 lb'},
            characteristics: { affection: -1, inquisitive: -1, bark: -1, odour: -1, sheddingAmount: -1},
            temperament: 'These rabbits love to play. Their energetic nature makes them ideal for families with younger children who have never had a pet before or for couples who want to take the next step in their relationship by caring for an adorable animal. Save for the initial purchases of their enclosures and the cost of the actual rabbit, they are relatively low-maintenance animals. They don’t require much grooming and simply need food, water and plenty of affection to keep them happy and healthy.',
            diet: 'As with all other rabbits, their diet should consist of 70-80 percent hay and grass with the rest of their meal consisting of fresh fruits and vegetables. Make sure your rabbit’s enclosure is dung-free, clean, and always has fresh water at their disposal.',
            housing: 'If your rabbit’s enclosure is outdoors, always be wary of the temperatures and weather forecast, as these factors can be a potential danger to your furry animal. Whether your enclosure is indoors or out, it’s best to keep this little guy happy with plenty of free time outside their cage. American Fuzzy Lops are active rabbits who love to run and jump round while basking in the sunlight, so a fenced backyard is recommended. If you live in an area where winters are particularly harsh and your Fuzzy Lop is indoors, they will still benefit from having time outside of their enclosures playing with their toys and cozying up with their favorite human.',
            toys: '' ,
            clean: 'Rabbits are clean animals when it comes to grooming themselves, and American Fuzzy Lops are no exception. These rabbits do not require daily grooming unless they are going through a molt. When this happens, simply run your fingers through their wool to work out any tangles and debris that may have gotten stuck in their coat.\n' +
            'You may also use a pet-specific brush if you don’t want to use your fingers, but under no circumstances should you fully bathe your rabbit; this causes them far too much stress. If you find a stain on your Fuzzy Lop’s coat, you can “spot clean” it with a damp cloth.',
            training: '',
            health: 'The American Fuzzy Lop is not at risk for any particular disease, however because its fur is so wooly, owners should watch out for Wool Block. Rabbits groom themselves like cats by licking their fur, but while cats can regurgitate the fur out of their system, rabbits cannot. When they eat too much of their own fur, their bodies tell them that they are full, when in reality, they are starving. If left untreated, they can die, so it’s important for owners to be aware of when and how much their rabbits eat at all times. Some owners uses papaya enzyme tablets, as the enzymes are supposed to help break down the furballs (since rabbits can’t regurgitate) and therefore prevent blockage.\n' +
            'To prevent worms developing in your rabbit’s stomach, de-worming paste twice a year is a must. This parasite can be ingested through your rabbit’s food like hay or grass, which is why it’s important to take preventative measures in order to protect them.\n' +
            'Also keep an eye on your rabbit’s fingernail and teeth growth to make sure they are not overgrowing. A rabbit’s teeth grow at an incredible rate and usually, they are shaved down by their high-hay and grass diet. However, some rabbits’ teeth still tend to overgrow and if this seems to be the case with your rabbit, there are several ways you can go about reducing their teeth length including giving them some rabbit-friendly wood to chew and play with.'
        }
    ]
};
