export const config = {
    port: process.env.PORT || 8080
};
export const breedAction = {
    SET_TOTAL_PAGE: "SET_TOTAL_PAGE",
    SET_CUR_PAGE: "SET_CUR_PAGE",
    GET_BREED_NAMES: "GET_BREED_NAMES",
    GET_BREEDS: "GET_BREEDS",
    UPDATE_BREEDS: "UPDATE_BREEDS",
    SET_SORT: "SET_SORT",
    SET_SEARCH: "SET_SEARCH",
    GET_BREED_BY_NAME: "GET_BREED_BY_NAME"
};
export const userAction = {
    UPDATE_USER: "UPDATE_USER",
    LOGIN_PENDING: "LOGIN_PENDING",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOG_OUT: "LOG_OUT",
    CHANGE_FORM: "CHANGE_USER_FORM",
    REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
    REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
    REGISTER_FAILURE: "USERS_REGISTER_FAILURE",
    RESET_FORM: "RESET_USER_FORM",
    CHANGE_FILTER: "CHANGE_FILTER"
};
export const utilAction = {
    SET_SPECIES_FILTER: "SET_SPECIES_FILTER",
    OPEN_MODAL: "OPEN_MODAL",
    DEL_PET: "DEL_PET",
    MODIFY_MODAL_PROPS: "MODIFY_MODAL_PROPS",
    ADD_EDIT_PET: "ADD_EDIT_PET",
    BREED_MODAL: "BREED_MODAL",
    USER_PET_MODAL: "USER_PET_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    ALTER: "ALTER"
};
export const speciesAction = {
    REQUEST_SPECIES: "REQUEST_SPECIES",
    GET_SPECIES: "GET_SPECIES"
};
